name: scan

on:
  push:
    branches:
      - "test"

jobs:
  container_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Hello from test!
        run: echo "Hello, container_scan!"
        env:
          SUPER_SECRET: ${{ secrets.SuperSecret }}